version: "3.9"
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./api/.env
    ports:
      - "27017:27017"
    # volumes:
    #   - node-mongo-data
  redis:
    image: redis:latest
    restart: unless-stopped
    env_file: ./api/.env
    ports:
      - "6379:6379"
  app:
    depends_on:
      - mongodb
      - redis
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: unless-stopped
    env_file: ./api/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_PORT=3000
#  ai-model:
#    build:
#      context: .
#      dockerfile: ./ai-model/Dockerfile
#    restart: unless-stopped
#    env_file: ./ai-model/.env
#    ports:
#      - "3002:3000"